services:
  backend:
    container_name: backend_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5200:5200"
    volumes:
      - .:/app
    # env_file:
    #   - .env

    restart: unless-stopped